spring.application.name=myportfolio
spring.datasource.url=jdbc:mysql://localhost:3306/myportfolio_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
# Use this for MySQL 8.0+
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.show-sql=tru


spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp


spring.servlet.multipart.max-file-size=5MB